server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.21.183.202:5432/loong_arch
    username: postgres
    password: woaini1314@!&
